name: Deploy & Register Flow
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prefect app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: | 
            cd projects/camara_bot_2.0
            export PYTHONPATH="${PYTHONPATH}:/root/projects/camara_bot_2.0/orm_database"
            git pull origin main
            echo 'Deployment successful to digital ocean'
            python3 tasks/orchestration_flow.py 
            echo 'Register flow successful' 
